### ISSUE TITLE
Exceptions happening during processing of requests

### ISSUE THREAD

**Issue by mkormendy** [insertjokehere/homemate-bridge#7]
So I'm getting two exception errors:

```
----------------------------------------
Exception happened during processing of request from ('192.168.2.102', 1883)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/site-packages/homemate_bridge/cli.py", line 180, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/homemate_bridge/cli.py", line 246, in handle
    packet = HomematePacket(data, self.keys)
  File "/usr/local/lib/python3.7/site-packages/homemate_bridge/cli.py", line 87, in __init__
    assert self.length == len(data)
```
and
```
----------------------------------------
Exception happened during processing of request from ('192.168.2.102', 31490)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/site-packages/homemate_bridge/cli.py", line 180, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/site-packages/homemate_bridge/cli.py", line 242, in handle
    data = self.request.recv(1024).strip()
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
```

Running this on a mac mini ... and everything else has been pretty flawless. The second exception causes the switch not to work anymore.

**Comment by mkormendy** [comment]
I'm getting rid of these cool outlets found something I can flash with an alternative firmware.
